implementing official redis in redis-0.7.0 adding logging to backup process testing

diff --git a/redis/templates/conf-backup-db.yaml b/redis/templates/conf-backup-db.yaml
--- a/redis/templates/conf-backup-db.yaml
+++ b/redis/templates/conf-backup-db.yaml
@@ -12,7 +12,11 @@ data:
     ## redis backup script
     ## usage
     ## redis-backup.sh port backup.dir
-    
+
+    now=$(date)
+
+    echo "Starting backup script at $now ..." > /data/backup.log
+
     port={{ .Values.service.port }}
     backup_dir=${2:-"/data/backup"}
     
@@ -24,16 +28,16 @@ data:
     aof_found=1
 
     test -f $rdb || {
-      echo "No RDB Found" ; rdb_found=0 #exit 1
+      echo "No RDB Found" >> /data/backup.log; rdb_found=0 #exit 1
     }
     
     test -f $aof || {
-      echo "No AOF Found" ; aof_found=0 #exit 1
+      echo "No AOF Found" >> /data/backup.log; aof_found=0 #exit 1
     }
     
     if [ $rdb_found -eq 0 ]; then
       if [ $aof_found -eq 0 ]; then
-        echo "No DBs found!"; exit 1
+        echo "No DBs found!" >> /data/backup.log; exit 1
       fi
     fi
 
@@ -43,7 +47,7 @@ data:
     
     # perform a bgsave before copy
     echo bgsave | $cli
-    echo "Waiting for 20 seconds..."
+    echo "Waiting for 20 seconds..." >> /data/backup.log
     sleep 20
     try=5
     while [ $try -gt 0 ] ; do
@@ -56,7 +60,7 @@ data:
         cp $rdb $dst_rdb
         #cp $aof $dst_aof
         if [ $? = 0 ] ; then
-          echo "Redis rdb $rdb copied to $dst_rdb."
+          echo "Redis rdb $rdb copied to $dst_rdb." >> /data/backup.log
     
           # delete rdb created {{ .Values.backup.deleteAfterDay }} days ago
           cd $backup_dir
@@ -67,7 +71,7 @@ data:
           fi
           cp $aof $dst_aof
           if [ $? = 0 ] ; then
-            echo "Redis aof $aof copied to $dst_aof."
+            echo "Redis aof $aof copied to $dst_aof." >> /data/backup.log
     
             # delete aof created {{ .Values.backup.deleteAfterDay }} days ago
             cd $backup_dir
@@ -75,16 +79,17 @@ data:
             exit 0
     
           else
-            echo "Failed to copy $aof to $dst_aof!"
+            echo "Failed to copy $aof to $dst_aof!" >> /data/backup.log
           fi
         else
-          echo "Failed to copy $rdb to $dst!"
+          echo "Failed to copy $rdb to $dst!" >> /data/backup.log
         fi
       fi
       try=$((try - 1))
-      echo "Redis maybe busy, waiting and retry in 5s..."
+      echo "Redis maybe busy, waiting and retry in 5s..." >> /data/backup.log
       sleep 5
     done
 
+    echo "Backup process finished!" >> /data/backup.log
 
 {{- end }}
